# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: testvm
#   namespace: vm
# spec:
#   hosts:
#     - '*'
#   gateways:
#     - istio-system/ingress
#   http:
#     - match:
#         - uri:
#             prefix: /payments
#       rewrite:
#         uri: "/"
#       route:
#         - destination:
#             host: testvm.vm.svc.cluster.local
#             port:
#               number: 8080
