# apiVersion: kubevirt.io/v1
# kind: VirtualMachineInstance
# metadata:
#   annotations:
#     sidecar.istio.io/inject: "true"
#   name: cirros-vmi
#   namespace: default
#   labels:
#     app: cirros-vmi
# spec:
#   domain:
#     devices:
#       interfaces:
#         - name: default
#           masquerade: {}
#           ports:
#             - name: http
#               port: 8080           
#       disks:
#         - disk:
#             bus: virtio
#           name: containerdisk
#         - disk:
#             bus: virtio
#           name: cloudinitdisk
#     resources:
#       requests:
#         memory: 128M
#   networks:
#     - name: default
#       pod: {}
#   terminationGracePeriodSeconds: 0
#   volumes:
#     - name: containerdisk
#       containerDisk:
#         image: kubevirt/cirros-container-disk-demo
#     - name: cloudinitdisk
#       cloudInitNoCloud:
#         userData: |
#           #cloud-config
#           users:
#             - name: cirros
#               passwd: gocubsgo
#           runcmd:
#             - echo '#!/bin/sh' > /webserver.sh
#             - echo 'while true; do' >> /webserver.sh
#             - echo '  (echo -e "HTTP/1.0 200 OK\r\n"; echo "Hello from testvm!") | nc -l -p 8080' >> /webserver.sh
#             - echo 'done' >> /webserver.sh
#             - chmod +x /webserver.sh
#             - nohup /webserver.sh > /var/log/webserver.log 2>&1 &