apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: testvm-dr
  namespace: payments
spec:
  host: testvm-service.payments.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE  # Test with simpler TLS first
