apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: testvm-dr
  namespace: default
spec:
  host: cirros-vmi-svc.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
