apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: disable-mtls
  namespace: payments
spec:
  selector:
    matchLabels:
      kubevirt.io/domain: testvm
  mtls:
    mode: DISABLE
