apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
  namespace: payment
spec:
  runStrategy: Always  # Ensure the VM is always running
  template:
    metadata:
      labels:
        kubevirt.io/domain: testvm
    spec:
      domain:
        resources:
          requests:
            memory: 128Mi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        machine:
          type: ""
      networks:
        - name: default
          pod: {}

      # readinessProbe:  # Add readiness probe for HTTP server health check
      #   httpGet:
      #     path: /
      #     port: 8080
      #   initialDelaySeconds: 5  # Wait 5 seconds before starting readiness checks
      #   periodSeconds: 10       # Check readiness every 10 seconds
      #   timeoutSeconds: 5       # Mark the probe as failed if no response in 5 seconds
      #   successThreshold: 1     # Minimum consecutive successes to be considered ready
      #   failureThreshold: 3     # Number of failures before marking unready

      volumes:
        - name: containerdisk
          containerDisk:
            image: kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: cirros
                  passwd: gocubsgo
              runcmd:
                - echo '#!/bin/sh' > /webserver.sh
                - echo 'while true; do' >> /webserver.sh
                - echo '  (echo -e "HTTP/1.0 200 OK\r\n"; echo "Hello from testvm!") | nc -l -p 8080' >> /webserver.sh
                - echo 'done' >> /webserver.sh
                - chmod +x /webserver.sh
                - nohup /webserver.sh > /var/log/webserver.log 2>&1 &


