apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: testvm-vs
  namespace: payment
spec:
  hosts:
    - testvm-service.payment.svc.cluster.local 
  gateways:
    - mesh  # Use the default Istio mesh gateway
  http:
    - match:
        - uri:
            prefix: /  # Match all traffic
      route:
        - destination:
            host: testvm-service.payment.svc.cluster.local 
            port:
              number: 8080
