Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "12288"
    vb.cpus = 8
  end

  config.vm.define "mesh" do |mesh|
    mesh.vm.hostname = "mesh"
    mesh.vm.network "public_network", ip: "192.168.1.10"

    # ArgoCD servers port forward for both clusters
    mesh.vm.network "forwarded_port", guest: 32000, host: 32000
    mesh.vm.network "forwarded_port", guest: 32002, host: 32002

    # Ingress controller port forward for first cluster
    mesh.vm.network "forwarded_port", guest: 31000, host: 31000
    mesh.vm.network "forwarded_port", guest: 31001, host: 31001

    # Ingress controller port forward for second cluster
    mesh.vm.network "forwarded_port", guest: 31002, host: 31002
    mesh.vm.network "forwarded_port", guest: 31003, host: 31003

    # Kube API server port forward for both clusters
    mesh.vm.network "forwarded_port", guest: 7443, host: 7443    
    mesh.vm.network "forwarded_port", guest: 8443, host: 8443

    # Provisioning with Ansible
    mesh.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "main.yml"
    end
  end
end
