Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "12288"
    vb.cpus = 8
  end

  config.vm.define "mesh" do |mesh|

    mesh.vm.hostname = "mesh"
    mesh.vm.network "public_network", ip: "192.168.1.10"  
    
    # argocd servers port forward for both clusters

    mesh.vm.network "forwarded_port", guest: 32000, host: 32000
    mesh.vm.network "forwarded_port", guest: 32001, host: 32001

    # ingress controller port forward for first cluster1
    mesh.vm.network "forwarded_port", guest: 31000, host: 31000
    mesh.vm.network "forwarded_port", guest: 31001, host: 31001 

    # ingress controller port forward for first cluster2
    mesh.vm.network "forwarded_port", guest: 31200, host: 31200
    mesh.vm.network "forwarded_port", guest: 31201, host: 31201     

    # kube api server port forward for first cluster1
    mesh.vm.network "forwarded_port", guest: 8443, host: 8443  
        
    mesh.vm.network "forwarded_port", guest: 8200, host: 9200  

    mesh.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "main.yml"

      ansible.extra_vars = {     
        "istio_igw_http_port_auh" => "33000",
        "istio_igw_http_port_dxb" => "33000",

        "istio_version" => "1.23.3",
        "istio_mesh_name" => "uaemesh"   

      }
    end
  end
end
