Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "12288"
    vb.cpus = 8
  end

  config.vm.define "mesh" do |mesh|

    mesh.vm.hostname = "mesh"
    mesh.vm.network "public_network", ip: "192.168.1.10"  
    
    mesh.vm.network "forwarded_port", guest: 32000, host: 32000
    mesh.vm.network "forwarded_port", guest: 32001, host: 32001

    mesh.vm.network "forwarded_port", guest: 33000, host: 33000
    mesh.vm.network "forwarded_port", guest: 33001, host: 33001  

    mesh.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "main.yml"

      ansible.extra_vars = { 
        "argo_node_port_auh" => "32000",
        "argo_node_port_dxb" => "32001",      

        "istio_igw_http_port_auh" => "33000",
        "istio_igw_http_port_dxb" => "33000",

        "istio_version" => "1.23.3",
        "istio_mesh_name" => "uaemesh"   

      }
    end
  end
end
