apiVersion: v1
kind: Service
metadata:
  name: testvm-service
  namespace: payments
spec:
  selector:
    kubevirt.io/domain: testvm
  ports:
    - protocol: TCP
      port: 8080        
      targetPort: 8080  
