---
- name: Check if Kind cluster exists
  command: kind get clusters
  register: kind_clusters
  changed_when: false

- name: Create Kind config file
  template:
    src: ./kind/{{ cluster.name }}/kind-config.yaml.j2
    dest: /tmp/kind-config.yaml
  when: cluster.name not in kind_clusters.stdout

- name: Create Kind cluster if it does not exist
  command: kind create cluster --name {{ cluster.name }} --config=/tmp/kind-config.yaml
  when: cluster.name not in kind_clusters.stdout

- name: Save Kind kubeconfig to guest machine
  shell: kind --name {{ cluster.name }} get kubeconfig > /tmp/kubeconfig-{{ cluster.name }}
  register: kubeconfig_save
  changed_when: false
  failed_when: kubeconfig_save.rc != 0
  when: cluster.name in kind_clusters.stdout or cluster.name not in kind_clusters.stdout

- name: Check if kubeconfig file exists on guest machine
  stat:
    path: /tmp/kubeconfig-{{ cluster.name }}
  register: kubeconfig_stat

- name: Debug kubeconfig save
  debug:
    msg: "Kubeconfig file creation status: {{ kubeconfig_stat.stat.exists }}"

- name: Fetch kubeconfig from guest to host
  fetch:
    src: /tmp/kubeconfig-{{ cluster.name }}
    dest: "./kubeconfig/{{ cluster.name }}"
    flat: yes
  when: kubeconfig_stat.stat.exists
