- name: Check if Kind cluster exists
  command: kind get clusters
  register: kind_clusters
  changed_when: false

- name: Create Kind config file
  template:
    src: ./kind/{{ cluster.name }}/kind-config.yaml.j2
    dest: /tmp/kind-config.yaml     
  when: cluster.name not in kind_clusters.stdout    
         
- name: Create Kind cluster if it does not exist
  command: kind create cluster --name {{ cluster.name }} --config=/tmp/kind-config.yaml
  when: cluster.name not in kind_clusters.stdout

