- name: Set virtctl version
  set_fact:
    virtctl_version: "v1.0.0"

- name: Check if virtctl is installed
  command: virtctl version
  register: virtctl_check
  failed_when: virtctl_check.rc not in [0, 127]
  ignore_errors: true

- name: Download virtctl binary
  get_url:
    url: "https://github.com/kubevirt/kubevirt/releases/download/{{ virtctl_version }}/virtctl-{{ virtctl_version }}-linux-amd64"
    dest: /tmp/virtctl
  when: virtctl_check.rc == 127

- name: Make virtctl binary executable
  file:
    path: /tmp/virtctl
    mode: '0755'
  when: virtctl_check.rc == 127

- name: Move virtctl binary to /usr/local/bin
  command: mv /tmp/virtctl /usr/local/bin/virtctl
  when: virtctl_check.rc == 127
