- name: Set Kind version
  set_fact:
    kind_version: "v0.20.0"

- name: Check if Kind is installed
  command: kind --version
  register: kind_check
  failed_when: kind_check.rc not in [0, 127]
  ignore_errors: true

- name: Download Kind binary
  get_url:
    url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
    dest: /tmp/kind
  when: kind_check.rc == 127

- name: Make Kind binary executable
  file:
    path: /tmp/kind
    mode: '0755'
  when: kind_check.rc == 127

- name: Move Kind binary to /usr/local/bin
  command: mv /tmp/kind /usr/local/bin/kind
  when: kind_check.rc == 127
