---
- name: Define Vault version and root token
  set_fact:
    vault_version: "1.16.0"  # Change this to the desired version
    vault_root_token: "root"

- name: Check if Vault CLI is installed
  command: vault --version
  register: vault_check
  failed_when: false
  changed_when: false

- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present
  when: ansible_os_family == "Debian"

- name: Download Vault CLI binary
  get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "/tmp/vault_{{ vault_version }}.zip"
    mode: '0644'
  when: "'Vault v' + vault_version not in (vault_check.stdout | default(''))"

- name: Unzip Vault CLI binary
  unarchive:
    src: "/tmp/vault_{{ vault_version }}.zip"
    dest: "/usr/local/bin/"
    remote_src: yes
  when: "'Vault v' + vault_version not in (vault_check.stdout | default(''))"

- name: Ensure Vault CLI binary is executable
  file:
    path: "/usr/local/bin/vault"
    mode: '0755'
  when: "'Vault v' + vault_version not in (vault_check.stdout | default(''))"

- name: Debug Vault CLI installation
  debug:
    msg: "Vault version installed: {{ vault_check.stdout }}"

- name: Install required packages for Vault (if not already installed)
  apt:
    name:
      - curl
      - unzip
    state: present
  become: true

- name: Start Vault in dev mode and keep it running
  shell: |
    nohup vault server -dev -dev-root-token-id="{{ vault_root_token }}" -log-level=trace > /tmp/vault.log 2>&1 &
  environment:
    VAULT_DEV_ROOT_TOKEN_ID: "{{ vault_root_token }}"
  args:
    executable: /bin/bash
  register: vault_process
  changed_when: false

- name: Ensure Vault server is accessible
  uri:
    url: "http://127.0.0.1:8200/v1/sys/seal-status"
    method: GET
    return_content: yes
    status_code: 200
  register: vault_health_check
  retries: 30
  delay: 5
  until: vault_health_check.status == 200

- name: Print Vault root token and process details
  debug:
    msg: >
      Vault is running in dev mode.
      Root token: {{ vault_root_token }}
      Vault log location: /tmp/vault.log
