---
- name: Set variables
  set_fact:
    remote_secret_dir: "remote-secrets"
    # api_server_port: 6443

- name: Ensure remote secrets directory exists
  file:
    path: "{{ remote_secret_dir }}"
    state: directory

- name: Get API Server pod IP for cluster {{ source_cluster.name }}
  shell: |
    kubectl --context {{ source_cluster.kubecontext }} get pod -n kube-system -l component=kube-apiserver -o jsonpath='{.items[0].status.podIP}'
  register: api_server_ip
  changed_when: false
  failed_when: api_server_ip.stdout == ''

- name: Display API server address and port
  debug:
    msg: "The Kubernetes API server address for {{ source_cluster.name }} is: https://{{ api_server_ip.stdout }}:{{ source_cluster.api_server_port }}"

- name: Create remote secret for cluster {{ source_cluster.name }} to be applied on {{ target_cluster.name }}
  shell: |
    istioctl create-remote-secret \
      --context {{ source_cluster.kubecontext }} \
      --server=https://{{ api_server_ip.stdout }}:{{ source_cluster.api_server_port }} \
      --name {{ source_cluster.name }} \
      > {{ remote_secret_dir }}/{{ source_cluster.name }}.yaml    
  when: api_server_ip.stdout is defined

- name: Apply the remote secret for cluster {{ source_cluster.name }} on {{ target_cluster.name }}
  shell: |
    kubectl --context {{ target_cluster.kubecontext }} apply -f {{ remote_secret_dir }}/{{ source_cluster.name }}.yaml
  when: api_server_ip.stdout is defined
